spring:
  application:
    name: microservicecloud-dept
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept-8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址
server:
  port: 8001
info:
  app.name: study-microservicecloud
  company.name: www.studyspringcloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
