eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  #      defaultZone: http://localhost:7001/eureka
  instance:
#    instance-id: microservicecloud-dept-8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC&amp    # 数据库名称，数据库5.8需要在链接上加上时间
    username: root
    password: 123456
    dbcp2:
      min-idle: 5   # 数据库连接池的最小维持连接数
      initial-size: 5  # 初始化连接数
      max-idle: 5        # 最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间
#mybatis
server:
  port: 8001
info:
  app.name: study-microservicecloud
  company.name: www.studyspringcloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
#这些功能涉及敏感信息，被监控端需要安全认证才能访问对应的监控点，添加配置可规避此异常：
management:
  security:
    enabled: false
#指定日志路径，保证admin可以监控的到
logging:
  file: D:\studyproject\log\dept.log
mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.sc.study.entitys # 所有Entity别名类所在包
  mapper-locations: classpath:/mapper/*.xml   # mapper映射文件

