eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  #      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址
    # 指定Eureka Client 间隔多久需要向EurekaServer 发送心跳来告知Eureka Server 该实例还存活
    lease-expiration-duration-in-seconds: 90
    #EurekaClient 向EurekaServer 发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 30
spring:
  application:
    name: microservicecloud-zuul-gateway
server:
  port: 9527
info:
  app.name: study-microservicecloud
  company.name: www.studyspringcloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
#这些功能涉及敏感信息，被监控端需要安全认证才能访问对应的监控点，添加配置可规避此异常：
management:
  security:
    enabled: false
#指定日志路径，保证admin可以监控的到
logging:
  file: D:\studyproject\log\zuul.log
#zuul 访问映射规则
zuul:
  prefix: /sc
  ignored-services: "*"
  routes:
    microservicecloud-dept.serviceId: microservicecloud-dept #解决 com.netflix.zuul.exception.ZuulException: Forwarding error
    microservicecloud-dept.path: /mydept/**

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000